version: '2'
# define all services
services:
  # our service is called CakePHP ;-)
  cakephp:
    # we want to use the image which is build from our Dockerfile
    build: .
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4000:80"
    # we depending on the mysql backend
    depends_on:
      - mariadb
    # we mount the working dir into the container, handy for development 
    volumes:
      - .:/var/www/html/
    environment:
      - SECURITY_SALT=ashjg23697sds97139871298ashk  
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
  mariadb:
    # we use the mysql base image, version 5.6.36
    image: mariadb:latest
    # we mount a datavolume to make sure we don't loose data
    volumes:
       - mariadb_data:/var/lib/mysql
       - ./simpleged.sql:/docker-entrypoint-initdb.d/dump.sql
    # setting some envvars to create the DB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=managecourier
volumes:
    mariadb_data:
